load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils",
    hdrs = ["utils.h", "stb_image_resize.h", "stb_image_write.h", "stb_image.h"],
    visibility = ["//main:__pkg__"],
    # visibility = ["//visibility:public"]
)